"""Render results.json as the generated results report (markdown)."""

from __future__ import annotations

from typing import Any

SURFACE_LABEL = {
    "generic": "generic (search/call)",
    "native_eager": "native eager",
    "native_deferred": "native deferred (SIMULATED)",
}


def _fmt(v: Any) -> str:
    if isinstance(v, float):
        return f"{v:,.2f}".rstrip("0").rstrip(".") if v != int(v) else f"{int(v):,}"
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, dict):
        return ", ".join(f"{k}={_fmt(x)}" for k, x in v.items())
    if isinstance(v, list):
        return ", ".join(_fmt(x) for x in v)
    return str(v)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(_fmt(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(out)


def render(results: dict[str, Any]) -> str:
    meta = results["meta"]
    lines: list[str] = []
    w = lines.append
    w("# Native-tool qualification: generated results (SC-125472)")
    w("")
    w("Generated by `python -m testmcpy.qualification run`; do not edit by hand. Every number")
    w("is labelled `measured`, `simulated` or `BLOCKED` (see `budgets.yaml` evidence classes).")
    w("")
    w(
        f"- Run: `{meta['run_id']}`; harness {meta['harness']}; budgets sha256 `{meta['budgets_sha256'][:16]}`"
        f" ({meta['budget_amendments']} amendments)"
    )
    w(
        f"- Tokenizer: `{meta['estimator']}`. Python {meta['python']}, mcp {meta['mcp']}, fastmcp {meta['fastmcp']}."
    )
    w("- All traffic is against in-process local fixtures. No live workspace was contacted.")
    w("")
    for cname, cm in results["catalogs"].items():
        n, g = cm["native"], cm["generic"]
        w(f"## Catalog `{cname}`")
        prov = cm.get("provenance", {})
        if cname == "actual":
            w(
                f"Real Superset MCP build `{prov.get('superset_sha', '?')[:10]}` "
                f"({prov.get('superset_commit_date', '?')}), fastmcp {prov.get('fastmcp_version', '?')}; "
                "metadata-only capture, no tool executed."
            )
        else:
            w(
                f"Synthetic scale catalog: {n['tool_count']} tools = the real catalog + "
                f"{cm['synthetic_tools']} derived clones (`{prov.get('synthetic_rule', '')}`)."
            )
        w("")
        rows = [
            ["native tools", n["tool_count"], n["total"], n["median"], n["p95"], n["max"]],
            [
                "generic surface (listed tools)",
                g["tool_count"],
                g["total"],
                g["median"],
                g["p95"],
                g["max"],
            ],
        ]
        w(_table(["definition set", "tools", "total tokens", "median", "p95", "max"], rows))
        w("")
        extra = [
            f"- Deferred initial context (tool-search def + pinned tools, simulated): "
            f"{_fmt(cm['native_deferred_initial'])} tokens"
        ]
        if cm.get("server_instructions_tokens") is not None:
            extra.append(
                f"- Server `instructions` (identical on every surface, not in B01): "
                f"{_fmt(cm['server_instructions_tokens'])} tokens"
            )
        if cm.get("output_schema_tokens_total") is not None:
            extra.append(
                f"- `outputSchema` payloads (not in B01/B02; counted only if a client forwards them): "
                f"{_fmt(cm['output_schema_tokens_total'])} tokens"
            )
        if cm.get("recorded_search_content_tokens_median") is not None:
            extra.append(
                f"- Real `search_tools` response, median over {len(cm['recorded_search_responses'])} "
                f"recorded queries: {_fmt(cm['recorded_search_content_tokens_median'])} tokens "
                "(`content` text only; `structuredContent` repeats the same data)"
            )
        extra.append(
            "- Heaviest native tools: " + ", ".join(f"`{k}` {v}" for k, v in n["heaviest"])
        )
        for e in extra:
            w(e)
        w("")
        w(f"### Surface metrics, catalog `{cname}`")
        w("")
        rows = []
        for surface in ("generic", "native_eager", "native_deferred"):
            m = results["metrics"][cname][surface]
            rows.append(
                [
                    SURFACE_LABEL[surface],
                    m["initial_tokens"],
                    m["task_total_tokens"]["median"],
                    m["task_total_tokens"]["p90"],
                    m["latency_ms"]["median"],
                    m["latency_ms"]["p95"],
                    m["discovery_round_trips"]["median"],
                    m["discovery_round_trips"]["max"],
                    m["accuracy_scripted"],
                    m["missing_tool_rate"],
                    m["arg_failure_rate"],
                    m["approvals"]["honours_annotations"]["read_only_task_mean"],
                    m["approvals"]["honours_annotations"]["write_task_per_write_op"],
                ]
            )
        w(
            _table(
                [
                    "surface",
                    "initial tok",
                    "task tok med",
                    "task tok p90",
                    "lat med ms",
                    "lat p95 ms",
                    "disc med",
                    "disc max",
                    "accuracy (scripted)",
                    "missing rate",
                    "arg-fail rate",
                    "approvals/read task",
                    "approvals/write op",
                ],
                rows,
            )
        )
        w("")
        w(
            "Approvals use the `honours_annotations` policy (simulated). Latency is in-process fixture time."
        )
        w("")
        w(f"### Per-task tokens (total / discovery round trips), catalog `{cname}`")
        w("")
        tasks = list(results["metrics"][cname]["generic"]["per_task"])
        rows = []
        for t in tasks:
            row: list[Any] = [t]
            for surface in ("generic", "native_eager", "native_deferred"):
                pt = results["metrics"][cname][surface]["per_task"][t]
                row.append(
                    f"{pt['total']:,} / {pt['discovery_rt']}" + ("" if pt["success"] else " FAIL")
                )
            rows.append(row)
        w(_table(["task", "generic", "native eager", "native deferred (sim)"], rows))
        w("")
        w(f"### Budget verdicts, catalog `{cname}`")
        w("")
        rows = []
        for v in results["verdicts"]:
            if v["catalog"] != cname:
                continue
            rows.append(
                [
                    v["budget"],
                    SURFACE_LABEL[v["surface"]],
                    v["value"],
                    v["hard_limit"],
                    v["status"],
                    "yes" if v["target_met"] else "no",
                    v["evidence"],
                    v["note"],
                ]
            )
        w(
            _table(
                [
                    "budget",
                    "surface",
                    "value",
                    "hard limit",
                    "status",
                    "target met",
                    "evidence",
                    "note",
                ],
                rows,
            )
        )
        w("")
    w("## tools/list pagination and completeness")
    w("")
    for cname, rows in results["pagination"].items():
        w(f"Catalog `{cname}`:")
        w("")
        w(
            _table(
                [
                    "page size",
                    "pages",
                    "expected",
                    "received",
                    "duplicates",
                    "completeness",
                    "first-page-only client sees",
                ],
                [
                    [
                        r["page_size"] or "all",
                        r["pages"],
                        r["expected"],
                        r["received"],
                        r["duplicates"],
                        r["completeness"],
                        r["first_page_only_coverage"],
                    ]
                    for r in rows
                ],
            )
        )
        w("")
    w("## Permission and workspace isolation probes")
    w("")
    iso = results["isolation"]
    w(
        f"{iso['probe_count']} probes, **{iso['leaks']} leaks** (measured on the fixture server, both surfaces)."
    )
    w("")
    w(
        _table(
            ["probe", "surface", "expected", "observed", "leak"],
            [
                [p["id"], p["surface"], p["expected"], p["observed"], "YES" if p["leak"] else "no"]
                for p in iso["probes"]
            ],
        )
    )
    w("")
    w("## Malformed-argument probes (where is a bad call rejected?)")
    w("")
    w(
        _table(
            ["probe", "surface", "rejected", "operation schema in tools/list", "server message"],
            [
                [
                    r["probe"],
                    r["surface"],
                    r["rejected"],
                    r["operation_schema_in_tools_list"],
                    r["message"],
                ]
                for r in results["argument_probes"]
            ],
        )
    )
    w("")
    fid = results.get("fidelity")
    if fid:
        w("## Result and error fidelity: native vs generic dispatcher (real Superset app)")
        w("")
        w(f"{fid['identical']}/{fid['total']} probes identical. Source: {fid['source']}.")
        w("")
        w(
            _table(
                ["probe", "flags identical", "text identical", "native text", "generic text"],
                [
                    [
                        c["probe"],
                        c["flags_identical"],
                        c["text_identical"],
                        c["native_text"],
                        c["generic_text"],
                    ]
                    for c in fid["compared"]
                ],
            )
        )
        w("")
    w("## Approval policy comparison (SIMULATED policies; mean prompts)")
    w("")
    for cname in results["metrics"]:
        w(f"Catalog `{cname}`:")
        w("")
        rows = []
        for surface in ("generic", "native_eager", "native_deferred"):
            ap = results["metrics"][cname][surface]["approvals"]
            for pol, vals in ap.items():
                rows.append(
                    [
                        SURFACE_LABEL[surface],
                        pol,
                        vals["read_only_task_mean"],
                        vals["write_task_per_write_op"],
                    ]
                )
        w(_table(["surface", "policy", "prompts per read-only task", "prompts per write op"], rows))
        w("")
    w(
        "`sql-query` counts as a read-only task, but the producer annotates `execute_sql` "
        "readOnlyHint=false, so it prompts under an annotation-honouring policy even on native tools."
    )
    w("")
    cr = results.get("client_runs")
    if cr:
        w("## Real-client spot runs (OBSERVED; local fixtures; OpenRouter route)")
        w("")
        w(
            f"Claude Code {cr['claude_code_version']}, {cr['codex_version']}. Prompt tokens are the client-reported "
            "input totals summed over all turns of the run (cache reads included), so single-turn "
            "`trivial` runs give first-turn context and task runs give cumulative cost. "
            "Raw sanitised traces: `traffic/clients/`."
        )
        w("")
        rows = []
        for r in cr["runs"]:
            rows.append(
                [
                    r["run"],
                    r["client"],
                    r["surface"],
                    r["catalog"],
                    r["task"],
                    r.get("tool_search_env") or ("approved" if r.get("approved") else ""),
                    r.get("mcp_tools_registered", ""),
                    r.get("turns", ""),
                    r["prompt_tokens_total"],
                    ", ".join(
                        c.replace("mcp__fixture__", "").replace("fixture.", "") for c in r["calls"]
                    )[:70],
                    ", ".join(d.replace("mcp__fixture__", "") for d in (r.get("denials") or [])),
                    {True: "yes", False: "NO", None: "n/a"}[r.get("answer_correct")],
                ]
            )
        w(
            _table(
                [
                    "run",
                    "client",
                    "surface",
                    "catalog",
                    "task",
                    "tool-search env / approve",
                    "mcp tools",
                    "turns",
                    "prompt tokens",
                    "tool calls",
                    "denied",
                    "answer correct",
                ],
                rows,
            )
        )
        w("")
    w("## BLOCKED / not measured")
    w("")
    for item in results["blocked"]:
        w(f"- **{item['what']}**: {item['reason']}")
    w("")
    return "\n".join(lines)
