"""
HTML eval suite report generator for testmcpy.

Produces self-contained HTML reports with embedded CSS (no external dependencies).
Dark theme with color-coded pass rates and categorized failure analysis.
"""

import re
from typing import Any

from testmcpy.src.report_generator import EvalSuiteReport


def _categorize_failure(reason: str) -> str:
    """Categorize a failure reason into a human-readable category."""
    lower = reason.lower()
    if "timeout" in lower or "timed out" in lower:
        return "Timeout"
    if "rate_limit" in lower or "429" in lower or "rate limit" in lower:
        return "Rate Limiting"
    if "connection" in lower or "network" in lower or "unreachable" in lower:
        return "Connection Error"
    if "auth" in lower or "unauthorized" in lower or "403" in lower or "401" in lower:
        return "Authentication Error"
    if "tool" in lower and ("not found" in lower or "not called" in lower):
        return "Tool Not Called"
    if "assertion" in lower or "expected" in lower or "mismatch" in lower:
        return "Assertion Failure"
    if "error" in lower or "exception" in lower:
        return "Runtime Error"
    return "Other"


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def _format_tokens(tokens: int) -> str:
    """Format token count for display."""
    if tokens >= 1_000_000:
        return f"{tokens / 1_000_000:.1f}M"
    if tokens >= 1_000:
        return f"{tokens / 1_000:.0f}K"
    return str(tokens)


def _score_color(score_str: str) -> str:
    """Return CSS color based on score percentage."""
    match = re.match(r"(\d+)", score_str)
    if not match:
        return "#e94560"
    pct = int(match.group(1))
    if pct >= 95:
        return "#4ecca3"
    if pct >= 80:
        return "#ffd369"
    return "#e94560"


class HTMLReportGenerator:
    """Generate rich HTML eval reports."""

    def __init__(self, report: EvalSuiteReport):
        self.report = report

    def generate(self) -> str:
        """Generate self-contained HTML string."""
        title = _escape_html(self.report.title or "Eval Suite Run")
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Eval Report - {title}</title>
    <style>{self._css()}</style>
</head>
<body>
    {self._header()}
    {self._grand_totals()}
    {self._per_eval_table()}
    {self._cost_summary()}
    {self._failures_section()}
    <footer>
        <p>Generated by testmcpy</p>
    </footer>
</body>
</html>"""

    def save(self, path: str) -> str:
        """Save HTML to file and return the path."""
        from pathlib import Path

        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.generate())
        return str(output_path)

    def _css(self) -> str:
        """Embedded CSS with dark theme."""
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                         Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #1a1a2e;
            color: #eee;
            padding: 2rem;
            line-height: 1.6;
        }
        h1 { color: #e94560; margin-bottom: 0.5rem; font-size: 1.8rem; }
        h2 { color: #e94560; margin: 2rem 0 1rem 0; font-size: 1.4rem; }
        h3 { color: #ffd369; margin: 1.5rem 0 0.5rem 0; font-size: 1.1rem; }
        .metadata { color: #aaa; margin-bottom: 0.3rem; font-size: 0.95rem; }
        .metadata code {
            background: #16213e;
            padding: 0.15rem 0.4rem;
            border-radius: 3px;
            font-size: 0.9rem;
        }
        hr {
            border: none;
            border-top: 1px solid #333;
            margin: 1.5rem 0;
        }

        /* Summary cards */
        .cards {
            display: flex;
            gap: 1rem;
            flex-wrap: wrap;
            margin: 1rem 0;
        }
        .card {
            background: #16213e;
            border-radius: 8px;
            padding: 1rem 1.5rem;
            min-width: 150px;
            flex: 1;
            text-align: center;
        }
        .card .label { color: #aaa; font-size: 0.85rem; text-transform: uppercase; }
        .card .value { font-size: 1.8rem; font-weight: bold; margin-top: 0.3rem; }

        /* Tables */
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            font-size: 0.95rem;
        }
        th {
            background: #16213e;
            color: #e94560;
            padding: 0.7rem 1rem;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #333;
        }
        td {
            padding: 0.6rem 1rem;
            border-bottom: 1px solid #2a2a3e;
        }
        tr:nth-child(even) td { background: rgba(22, 33, 62, 0.4); }
        tr:hover td { background: rgba(233, 69, 96, 0.1); }
        tr.total-row td {
            font-weight: bold;
            border-top: 2px solid #e94560;
            background: rgba(233, 69, 96, 0.05);
        }

        .pass { color: #4ecca3; }
        .fail { color: #e94560; }
        .skip { color: #888; }
        .score { font-weight: bold; }

        /* Failure list */
        .failure-item {
            background: #16213e;
            border-left: 3px solid #e94560;
            padding: 0.7rem 1rem;
            margin: 0.5rem 0;
            border-radius: 0 4px 4px 0;
        }
        .failure-item .test-name { color: #ffd369; font-weight: 600; }
        .failure-item .reason { color: #ccc; font-size: 0.9rem; margin-top: 0.2rem; }

        /* Cost cards */
        .cost-item {
            background: #16213e;
            padding: 0.7rem 1rem;
            margin: 0.4rem 0;
            border-radius: 6px;
        }
        .cost-item .cost-label { color: #aaa; }
        .cost-item .cost-value { color: #4ecca3; font-weight: bold; }
        .cost-total {
            background: rgba(233, 69, 96, 0.15);
            border: 1px solid #e94560;
        }

        footer {
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid #333;
            color: #555;
            font-size: 0.85rem;
            text-align: center;
        }
        """

    def _header(self) -> str:
        """Report header with metadata."""
        title = _escape_html(self.report.title or "Eval Suite Run")
        lines = [f"<h1>Eval Suite Results &mdash; {title}</h1>"]

        if self.report.workspace_hash:
            lines.append(
                f'<p class="metadata"><strong>Workspace:</strong> '
                f"<code>{_escape_html(self.report.workspace_hash)}</code>"
                f" on <code>{_escape_html(self.report.domain)}</code></p>"
            )
        if self.report.build_slug:
            lines.append(
                f'<p class="metadata"><strong>Build:</strong> '
                f"<code>{_escape_html(self.report.build_slug)}</code></p>"
            )
        lines.append(
            f'<p class="metadata"><strong>Date:</strong> {_escape_html(self.report.date)}</p>'
        )
        lines.append(
            f'<p class="metadata"><strong>Run by:</strong> {_escape_html(self.report.run_by)}</p>'
        )
        lines.append("<hr>")
        return "\n    ".join(lines)

    def _grand_totals(self) -> str:
        """Grand totals with summary cards and color-coded scores."""
        grand_tests = 0
        grand_pass = 0
        grand_fail = 0
        grand_skip = 0

        for data in self.report.suite_results.values():
            grand_tests += data["tests"]
            grand_pass += data["pass"]
            grand_fail += data["fail"]
            grand_skip += data["skip"]

        total_for_score = grand_pass + grand_fail
        grand_score = (
            f"{(grand_pass / total_for_score * 100):.0f}%" if total_for_score > 0 else "0%"
        )
        score_clr = _score_color(grand_score)

        # Summary cards
        cards = f"""
    <div class="cards">
        <div class="card">
            <div class="label">Total Tests</div>
            <div class="value" style="color: #eee;">{grand_tests}</div>
        </div>
        <div class="card">
            <div class="label">Pass Rate</div>
            <div class="value" style="color: {score_clr};">{grand_score}</div>
        </div>
        <div class="card">
            <div class="label">Passed</div>
            <div class="value pass">{grand_pass}</div>
        </div>
        <div class="card">
            <div class="label">Failed</div>
            <div class="value fail">{grand_fail}</div>
        </div>
    </div>"""

        # Grand totals table
        rows = []
        for suite_name, data in self.report.suite_results.items():
            s_color = _score_color(data["score"])
            rows.append(
                f"        <tr>"
                f"<td>{_escape_html(suite_name)}</td>"
                f"<td>{data['tests']}</td>"
                f'<td class="pass">{data["pass"]}</td>'
                f'<td class="fail">{data["fail"]}</td>'
                f'<td class="skip">{data["skip"]}</td>'
                f'<td class="score" style="color: {s_color};">{data["score"]}</td>'
                f"</tr>"
            )

        # Grand total row
        rows.append(
            f'        <tr class="total-row">'
            f"<td>Total</td>"
            f"<td>{grand_tests}</td>"
            f'<td class="pass">{grand_pass}</td>'
            f'<td class="fail">{grand_fail}</td>'
            f'<td class="skip">{grand_skip}</td>'
            f'<td class="score" style="color: {score_clr};">{grand_score}</td>'
            f"</tr>"
        )

        table = f"""
    <h2>Grand Totals</h2>
    <table>
        <thead>
            <tr><th>Suite</th><th>Tests</th><th>Pass</th><th>Fail</th><th>Skip</th><th>Score</th></tr>
        </thead>
        <tbody>
{chr(10).join(rows)}
        </tbody>
    </table>"""

        return cards + table

    def _per_eval_table(self) -> str:
        """Per-eval breakdown tables grouped by suite."""
        sections = []

        for suite_name, data in self.report.suite_results.items():
            results = data.get("results", [])
            if not results:
                continue

            rows = []
            for i, r in enumerate(results, 1):
                test_name = r.get("test_name") or r.get("name") or f"test_{i}"
                passed = r.get("passed", False)
                skipped = r.get("skipped", False)

                if skipped:
                    status_td = '<td class="skip">SKIP</td>'
                    notes = "SKIPPED"
                elif passed:
                    status_td = '<td class="pass">PASS</td>'
                    notes = ""
                else:
                    status_td = '<td class="fail">FAIL</td>'
                    notes = _escape_html(r.get("reason") or r.get("error") or "Failed")

                rows.append(
                    f"        <tr>"
                    f"<td>{i:02d}</td>"
                    f"<td>{_escape_html(test_name)}</td>"
                    f"{status_td}"
                    f"<td>{notes}</td>"
                    f"</tr>"
                )

            section = f"""
    <h2>{_escape_html(suite_name)} &mdash; Eval Results</h2>
    <table>
        <thead>
            <tr><th>#</th><th>Test</th><th>Status</th><th>Notes</th></tr>
        </thead>
        <tbody>
{chr(10).join(rows)}
        </tbody>
    </table>"""
            sections.append(section)

        return "\n".join(sections)

    def _cost_summary(self) -> str:
        """Cost and token summary cards."""
        items = []

        if self.report.mcp_direct_tool_calls > 0 or self.report.mcp_direct_tokens > 0:
            tokens_str = _format_tokens(self.report.mcp_direct_tokens)
            items.append(
                f'    <div class="cost-item">'
                f'<span class="cost-label">MCP Direct:</span> '
                f"~{self.report.mcp_direct_tool_calls} tool calls, "
                f"~{tokens_str} tokens, "
                f'<span class="cost-value">~${self.report.mcp_direct_cost:.2f}</span>'
                f"</div>"
            )

        if self.report.chatbot_requests > 0 or self.report.chatbot_tokens > 0:
            tokens_str = _format_tokens(self.report.chatbot_tokens)
            items.append(
                f'    <div class="cost-item">'
                f'<span class="cost-label">Chatbot Pipeline:</span> '
                f"~{self.report.chatbot_requests} requests, "
                f"~{tokens_str} tokens, "
                f'<span class="cost-value">~${self.report.chatbot_cost:.2f}</span>'
                f"</div>"
            )

        items.append(
            f'    <div class="cost-item cost-total">'
            f'<span class="cost-label">Total eval cost:</span> '
            f'<span class="cost-value">~${self.report.total_cost:.2f}</span>'
            f"</div>"
        )

        return f"""
    <h2>Cost and Token Summary</h2>
{chr(10).join(items)}"""

    def _failures_section(self) -> str:
        """Failures grouped by category."""
        failures: list[dict[str, Any]] = []
        for suite_name, data in self.report.suite_results.items():
            for r in data.get("results", []):
                if not r.get("passed") and not r.get("skipped"):
                    failures.append(
                        {
                            "suite": suite_name,
                            "test": r.get("test_name") or r.get("name") or "unknown",
                            "reason": r.get("reason") or r.get("error") or "Unknown failure",
                        }
                    )

        if not failures:
            return """
    <h2>Failures Analysis</h2>
    <p style="color: #4ecca3;">No failures detected.</p>"""

        categories: dict[str, list[dict[str, str]]] = {}
        for f in failures:
            category = _categorize_failure(f["reason"])
            if category not in categories:
                categories[category] = []
            categories[category].append(f)

        sections = ["<h2>Failures Analysis</h2>"]
        for category, items in categories.items():
            sections.append(f"    <h3>{_escape_html(category)} ({len(items)})</h3>")
            for item in items:
                suite = _escape_html(item["suite"])
                test = _escape_html(item["test"])
                reason = _escape_html(item["reason"])
                sections.append(
                    f'    <div class="failure-item">'
                    f'<div class="test-name">{suite} / {test}</div>'
                    f'<div class="reason">{reason}</div>'
                    f"</div>"
                )

        return "\n".join(sections)
